### PR TITLE
Sachin'sMiniProj

### PR DESCRIPTION
**Pull request by SachinM123**
This is my completely mini project. It functions as intended. It is able to receive the correct input from a joystick. Naher has checked project, has not been tested with actual motor just simulation.

### CODE REVIEW

**Comment by josieammer** [comment]
This code doesn't implement the intended functionality.  The motor is not connected to the joystick.  
To debug this, try adding some print statements to your NeoMotors.java in the setMotorSpeed and MotorStop methods.  Then run the simulation and see if changing the joystick actually changes the motor speed in the console.

**Comment by mmcadamsms** [comment]
Seems like this project is almost the same as Naher's project.  I think I'd rather see you Sachin to pickup a project that is different from Naher's project.  You up for it?

**Comment by SachinM123** [comment]
Sure.

**Review by mmcadamsms — COMMENTED** [review]
General Comment: @SachinM123 can you close this review, the other one you have has superseded this one.

**Pull request closed without merging**
